language: elixir

branches:
  only:
    - "master"

matrix:
  include:
    - elixir: 1.4
      otp_release: 19.3
    - elixir: 1.5
      otp_release: 19.3
    - elixir: 1.6
      otp_release: 19.3
    - elixir: 1.6
      otp_release: 20.2
      env: COVERALLS=true

sudo: required
dist: trusty
services: docker

python:
  - "3.6"
virtualenv:
  system_site_packages: true
addons:
  apt:
    packages:
      - "python3-pip"

env:
  - COVERALLS=false

install:
  - pip3 install --user thrift==0.10.0
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get

script:
  - MIX_ENV=test mix deps.compile
  - ./ci/tests.sh

cache:
  directories:
  - $HOME/.mix/archives
